[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Forensics: Investigating the Role of Intelligent Technologies in Criminal Investigations"
